GN-4435: Use `cool-uri` to create permalink for `zitting`
lblod/app-gn-publicatie pull request #34
Opened 2023-10-06 09:29 UTC by dkozickis

### Overview

GN-4435: Use `cool-uri` to create permalink for `zitting`

Setup `cool-uri` service to provide permalinks for `zitting` (and other entities via `/permalink`)

##### connected issues and PRs:

https://binnenland.atlassian.net/browse/GN-4435
https://github.com/lblod/besluit-publicatie-publish-service/pull/11

### Setup

1. Checkout
2. Checkout this PR https://github.com/lblod/besluit-publicatie-publish-service/pull/11 for `besluit-publicatie-publish-service`
3. Add following to `docker-compose.override.yml` 
   ```docker
    version: "3.4"
    services:
      besluit-publicatie:
        image: mu-javascript-template:latest
        environment:
          NODE_ENV: "development"
        volumes:
          - ./data/files/:/share/
          - /<LOCATION_OF_BESLUIT_SERVICE>/:/app/
   ```

Where `<LOCATION_OF_BESLUIT_SERVICE>` is folder where the `besluit-publicatie-publish-service` is checked out

4. `docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.override.yml up`

### How to test/reproduce

Confirm that migration was executed by running below query at http://localhost:8080/sparql

```sparql
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT * WHERE {
  ?permalink foaf:page ?redirect .
} LIMIT 10
```

1. Try to access http://localhost:8080/Huldenberg/Gemeente/zitting/b2f47ed1-3534-11e9-a984-7db43f975d75, confirm you are redirected to http://localhost:8080/Huldenberg/Gemeente/zittingen/b2f47ed1-3534-11e9-a984-7db43f975d75 (note `zitting` vs `zittingen` in URL)
2. Try to access http://localhost:8080/permalink?uri=http://data.lblod.info/id/zittingen/8c93d2cc-f4ba-4444-b09e-b7495e336ff8, confirm you are redirected to http://localhost:8080/Huldenberg/Gemeente/zittingen/b2f47ed1-3534-11e9-a984-7db43f975d75
5. Call `curl -v http://localhost:8080/permalink?uri=http://data.lblod.info/id/zittingen/8c93d2cc-f4ba-4444-b09e-b7495e336ff8`, confirm you get `HTTP/1.1 303 See Other` and `location: /Huldenberg/Gemeente/zittingen/b2f47ed1-3534-11e9-a984-7db43f975d75` in the response headers

Confirm that besluit service is inserting permalink by either publishing something from GN, if you have it setup, or going to http://localhost:8080/sparql and executing following query

```sparql
PREFIX sign: <http://mu.semte.ch/vocabularies/ext/signing/>

INSERT DATA {
GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/published-resources/0cf4b620-45f9-11ec-99f4-b935d359b4a5> a sign:PublishedResource ;
        <http://purl.org/dc/terms/created> "2023-10-04T09:47:30.818Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        sign:text """<div class="au-c-template au-c-template--treatment behandeling"
     prefix="eli: http://data.europa.eu/eli/ontology# prov: http://www.w3.org/ns/prov# mandaat: http://data.vlaanderen.be/ns/mandaat# besluit: http://data.vlaanderen.be/ns/besluit# ext: http://mu.semte.ch/vocabularies/ext/ person: http://www.w3.org/ns/person# persoon: http://data.vlaanderen.be/ns/persoon# dateplugin: http://say.data.gift/manipulators/insertion/ besluittype: https://data.vlaanderen.be/id/concept/BesluitType/ dct: http://purl.org/dc/terms/ mobiliteit: https://data.vlaanderen.be/ns/mobiliteit# lblodmow: http://data.lblod.info/vocabularies/mobiliteit/">
    <div about="http://data.lblod.info/id/zittingen/6515CDF42C0D037764237179" typeof="besluit:Zitting"><span
            property="http://data.vlaanderen.be/ns/besluit#isGehoudenDoor"
            resource="http://data.lblod.info/id/bestuursorganen/28dca2b0f60eb33cdb72e8398fa63e19352f8fa67dfaa3a7784d83498d521bcf"></span>
        <span property="http://data.vlaanderen.be/ns/besluit#geplandeStart" content="2023-09-28T17:00:51.870Z"
              datatype="http://www.w3.org/2001/XMLSchema#dateTime"></span> <span
                property="http://www.w3.org/ns/prov#startedAtTime" content="2023-09-28T17:00:51.870Z"
                datatype="http://www.w3.org/2001/XMLSchema#dateTime" class="is-required"></span> <span
                property="http://www.w3.org/ns/prov#endedAtTime" content="2023-09-28T19:05:26.580Z"
                datatype="http://www.w3.org/2001/XMLSchema#dateTime"></span>
        <div class="au-c-template au-c-template--treatment" typeof="besluit:BehandelingVanAgendapunt"
             resource="http://data.lblod.info/id/behandelingen-van-agendapunten/6515CE5F2C0D03776423717A"><p
                content="true" datatype="xsd:boolean" property="besluit:openbaar"><span class="au-c-template-public">Openbare behandeling van agendapunt</span>
        </p>
            <h3 resource="http://data.lblod.info/id/agendapunten/6515CE602C0D03776423717B" property="dc:subject"><span
                    property="dc:title">besluit mbt vastgoedinformatieplatform</span> (<span
                    property="besluit:Agendapunt.type"
                    resource="http://lblod.data.gift/concepts/bdf68a65-ce15-42c8-ae1b-19eeb39e20d0"
                    typeof="skos:Concept">gepland</span>) </h3> <h4>Aanwezigen bij agendapunt</h4>

            <h4>Stemmingen bij agendapunt</h4>
            <div class="c-template-content c-template-content--treatment"></div>
        </div>
    </div>
</div>
""" .
}
}
```

Then after running 

```sparql
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT * WHERE {
  <http://data.lblod.info/id/zittingen/6515CDF42C0D037764237179> foaf:page ?redirect .
} LIMIT 10
```

You should be able to observe something like this, note that the ID part of the URL will be different

<img width="560" alt="CleanShot 2023-10-09 at 11 14 09@2x" src="https://github.com/lblod/app-gn-publicatie/assets/769698/c06a3402-8000-4a48-97f2-4afe7cad162c">

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] no new deprecations

2023-10-06 11:16 UTC, abeforgit requested changes

2023-10-06 11:16 UTC, abeforgit commented on config/dispatcher/dispatcher.ex
> +  # This will catch calls to links like {HOST}/Aalst/Gemeente/zitting/b2f47ed1-3534-11e9-a984-7db43f975d75
for backwards compat I think we can just forward directly without having to pass through the cooluri service?

2023-10-06 11:16 UTC, abeforgit commented on config/dispatcher/dispatcher.ex
> +  match "/permalink/*path", @any do
I'd like to see the actual uri of the requested resource used here, as discussed on rocket (if possible)
this means any visitor could visit `https://publicatie.gelinkt-notuleren.vlaanderen.be/permalink?uri=<uri>` and get the content for that resource

2023-10-06 14:52 UTC, piemonkey reviewed
Am I right in thinking the behaviour after the initial redirect isn't defined yet? Locally I get a strange 307 redirect after the first one (using httpie), e.g.

```
http :8080/Huldenberg/Gemeente/zitting/4b60e8f1-3532-11e9-a984-7db43f975d75
# HTTP/1.1 303 See Other
# location: /Langemark-Poelkapelle/Gemeente/zittingen/4b60e8f1-3532-11e9-a984-7db43f975d75
http :8080/Langemark-Poelkapelle/Gemeente/zittingen/4b60e8f1-3532-11e9-a984-7db43f975d75
# HTTP/1.1 307 Temporary Redirect
# location: //localhost:8080/Langemark-Poelkapelle/Gemeente
```

2023-10-06 14:52 UTC, piemonkey commented on config/dispatcher/dispatcher.ex
> +  match "/:bestuurseenheid_naam/:bestuurseenheid_classificatie_code_label/zitting/:id", @any do
Am I missing something about how `mu-dispatcher` matches paths, or would this cause problems if we ever had a route in the UI which had 2 parts and then the word `zitting`? I feel like there should be a literal first part of the path to avoid collisions.

2023-10-09 08:20 UTC, piemonkey commented on config/dispatcher/dispatcher.ex
> +  match "/:bestuurseenheid_naam/:bestuurseenheid_classificatie_code_label/zitting/:id", @any do
Hmm, that was for an id I got from the triplestore though, so I thought it should exist, unless I managed to use the wrong id.

2023-10-16 08:36 UTC, abeforgit commented on config/dispatcher/dispatcher.ex
> +  match "/:bestuurseenheid_naam/:bestuurseenheid_classificatie_code_label/zitting/:id", @any do
I for one can't reproduce your issue @piemonkey 
I get a 301, which is correct, and `--follow` can follow nicely

2023-10-16 11:10 UTC, merged